config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'user/login_form'

  post 'user/login'

  get 'user/logout'

  get 'user/new'

  post 'user/create'
  
  get 'user/verify'
  
  get 'user/forgot_form'
  
  post 'user/forgot'
  
  get 'user/forgot_change'
  
  post 'user/forgot_confirm'
  

  get 'comment/new'

  get 'comment/create'

  get 'comment/delete'

  get 'post/create'

  get 'post/new'
  
  get 'post/modify'
  
  get 'post/update'
  
  get 'post/delete'
  
  root 'post#list'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    resourcify
    include Authority::Abilities
    
    belongs_to :post
    belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
    resourcify
    include Authority::Abilities
    
    has_many :comments
    belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  rolify
  include Authority::UserAbilities
  
  has_many :posts
  has_many :comments
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/models/verification.rb
class Verification < ActiveRecord::Base
    belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # before_filter :require_login
  
  protected  
  
  def require_login
    @logined_user = logged_in?
    if not @logined_user
      redirect_to controller: 'user', action: 'login_form'
    end
  end
  
  def logged_in?
    if session[:logined]
      current_user = session[:user]
      return current_user
    end
    return false
  end
  
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @_id = params[:id]
  end

  def create
    _id = params[:id]
    _contents = params[:contents]
    
    _post = Post.find(_id)
    
    comment = Comment.new(post: _post, contents: _contents)
    comment.user = current_user
    comment.save
    
    redirect_to controller: 'post', action:'list'
  end

  def delete
    authorize_action_for @post
    
    _id = params[:id]
    
    comment = Comment.find(_id)
    comment.destroy
    
    redirect_to controller: 'post', action:'list'
    
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  
  # skip_before_filter :require_login, :only => [:list]
  before_action :authenticate_user!, except: [ :list ]
  
  def create
    _author = params[:author]
    _title = params[:title]
    _contents = params[:contents]
    
    post = Post.new(author: _author, title: _title, contents: _contents) ## record / row
    post.user = current_user
    post.save
    
    redirect_to controller:'post', action:'list'
  end

  def new
    
  end
  
  def list
    @posts = Post.all
    
  end
  
  def modify
     
    _id = params[:id]
    @post = Post.find(_id)
    authorize_action_for @post
    
  end
  
  def update 
     
    _id = params[:id]
    _author = params[:author]
    _title = params[:title]
    _contents = params[:contents]
    
    @post = Post.find(_id)
    authorize_action_for @post
    
    @post.author = _author
    @post.title = _title
    @post.contents = _contents
    
    @post.save
    
    redirect_to controller: 'post', action: 'list'
  end
  
  def delete
     
    _id = params[:id]
    
    @post = Post.find(_id)
    authorize_action_for @post
    @post.destroy
    
    redirect_to controller: 'post', action: 'list'
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  # skip_before_filter :require_login, :only => [:login_form, :login, :new, :create, :verify, :forgot, :forgot_change, :forgot_confirm, :forgot_form]
  
  def login_form
    
  end

  def login
    _account = params[:account]
    _password = params[:password]
    
    user = User.find_by(account: _account)
    
    if user == nil 
      flash[:error] = "존재하지 않는 계정입니다."
      redirect_to :back
      return 
    end
      
    
    if user.password == Digest::SHA256.hexdigest(_password)
      if user.is_verified == false 
        flash[:error] = "이메일 인증을 완료해주세요."
        redirect_to :back
        return 
      end
      
      ## success
      session[:logined] = true
      session[:user] = user
      redirect_to controller: 'post', action: 'list'
    else
      ## failure
      flash[:error] = "비밀번호를 확인해주세요."
      redirect_to :back
    end
    
  end

  def logout
    reset_session
    
    redirect_to controller: 'post', action: 'list'
  end

  def new
  end

  def create
    _account = params[:account]
    _password = params[:password]
    _name = params[:name]
    _email = params[:email]
    
    if User.find_by(account: _account) != nil
      redirect_to :back
      return 
    end
    
    user = User.new
    user.account = _account
    user.password = Digest::SHA256.hexdigest(_password)
    user.name = _name
    user.email = _email 
    user.save
    
    ##
    verification = Verification.new 
    verification.user = user 
    verification.code = SecureRandom.hex(16) ## 16자리 코드
    verification.save 
    
    UserMailer.signup(user, verification).deliver
    
    redirect_to controller: 'post', action: 'list'
  end
  
  def verify 
    _code = params[:code]
    
    verification = Verification.find_by(code: _code)
    
    if verification == nil or verification.is_active == false 
      flash[:error] = "인증이 만료되었습니다."
      redirect_to '/'
      return 
    end
    
    user = verification.user
    user.is_verified = true 
    user.save 
    
    verification.is_verified = true 
    verification.is_active = false 
    verification.save 
    
    flash[:success] = "인증이 완료되었습니다. 로그인을 해주세요."
    
    UserMailer.welcome(user).deliver
    
    redirect_to controller: 'user', action:'login_form'
  end
  
  def forgot_form
    
  end
  
  def forgot 
    _email = params[:email]
    
    user = User.find_by(email: _email)
    
    if user == nil or user.is_verified == false 
      flash[:error] = "존재하지 않는 계정입니다."
      redirect_to :back
      return 
    end
    
    ##
    verification = Verification.new 
    verification.user = user 
    verification.code = SecureRandom.hex(16) ## 16자리 코드
    verification.save 
    
    UserMailer.forgot(user, verification).deliver
    
    flash[:success] = "이메일을 확인해주세요."
    
    redirect_to controller: 'user', action:'login_form'
  end
  
  def forgot_change 
    _code = params[:code]
    
    verification = Verification.find_by(code: _code)
    
    if verification == nil or verification.is_active == false or verification.user.is_verified == false 
      flash[:error] = "정상적인 접근이 아닙니다."
      redirect_to '/'
      return 
    end
    
    @verification = verification
  end
  
  def forgot_confirm
    _code = params[:code]
    _password = params[:password]
    
    verification = Verification.find_by(code: _code)
    
    if verification == nil or verification.is_active == false or verification.user.is_verified == false 
      flash[:error] = "정상적인 접근이 아닙니다."
      redirect_to '/'
      return 
    end
    
    user = verification.user 
    user.password = Digest::SHA256.hexdigest(_password)
    user.save
    
    verification.is_active = false 
    verification.save 
    
    flash[:success] = "비밀번호 변경이 완료되었습니다."
    
    redirect_to controller: 'user', action:'login_form'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comment/create.html.erb
<h1>Comment#create</h1>
<p>Find me in app/views/comment/create.html.erb</p>

app/views/comment/delete.html.erb
<h1>Comment#delete</h1>
<p>Find me in app/views/comment/delete.html.erb</p>

app/views/comment/new.html.erb
<h1>댓글 작성</h1>
<form action="/comment/create">
    <input type="hidden" name="id" value="<%=@_id%>">
    <input type="text" name="contents">
    <button type="submit">작성</button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/post/create.html.erb
<h1>Post#create</h1>
<p>Find me in app/views/post/create.html.erb</p>

app/views/post/list.html.erb
<h3>방명록 리스트</h3>
<a href="/post/new" style="float:right;display:inline-block;">
    <button>새 글</button>
</a>

	<% if user_signed_in? %>
	  <p>현재 로그인된 유저의 이메일 : <%= current_user.email %></p>
	  <p><%= link_to "로그아웃", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %></p>
	<% else %>
	  <p><%= link_to "로그인", new_user_session_path %></p>
	<% end %>
	
<ul>
    <% @posts.each do |post| %>
    <li>
        <h4><%=post.id%>, <%=post.title%></h4>
        
    		<% if user_signed_in? %>
    		  <%= link_to '수정', post_modify_path(post) if post.updatable_by? current_user %>&nbsp;
    		  <%= link_to '삭제', post_delete_path(post), data: { confirm: 'Are you sure?' } if post.deletable_by? current_user %>
    		<% end %>
            <!--<a href="/post/modify?id=<%=post.id%>">수정</a>-->
            <!--<a href="/post/delete?id=<%=post.id%>">삭제</a>-->
            <a href="/comment/new?id=<%=post.id%>">댓글</a>
        <hr>
        <%=post.contents%>
        <hr>
        <%=post.author%>, <%=post.created_at.in_time_zone(9).to_formatted_s(:short)  %>
        
        <hr>
        <ol>
        <% post.comments.each do |comment| %>
            <li><%=comment.contents%>, <a href="/comment/delete?id=<%=comment.id%>">X</a></li>
        <% end %>
        </ol>
    </li>
    <% end %>
</ul>

app/views/post/modify.html.erb
<h1>글 수정하기</h1>
<form action="/post/update">
    <input type="hidden" name="id" value="<%=@post.id%>">
    <p>
        <label for="title">제목</label>
        <input type="text" name="title" value="<%=@post.title%>">
    </p>
    
    <p>
        <label for="author">작성자</label>
        <input type="text" name="author" value="<%=@post.author%>">
    </p>
    <hr>
    <textarea name="contents"><%=@post.contents%></textarea>
    <button type="submit">수정하기!</button>
</form>

app/views/post/new.html.erb
<h1>Post#new</h1>
<form action="/post/create">
    <p>
        <label for="title">제목</label>
        <input type="text" name="title">
    </p>
    
    <p>
        <label for="author">작성자</label>
        <input type="text" name="author">
    </p>
    <hr>
    <textarea name="contents"></textarea>
    <button type="submit">글쓰기!</button>
</form>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/forgot_change.erb
<h1>비밀번호 변경</h1>
<form action="/user/forgot_confirm" method="post">
    <%= hidden_field_tag(request_forgery_protection_token.to_s, form_authenticity_token) %>
    <input type="hidden" name="code" value="<%=@verification.code%>">
    <p>
        <label for="password">새 비밀번호</label>
        <input name="password" type="password">
    </p>
    <button type="submit">확인</button>
</form>

app/views/user/forgot_form.erb
<h1>비밀번호 찾기</h1>
<form action="/user/forgot" method="post">
    <%= hidden_field_tag(request_forgery_protection_token.to_s, form_authenticity_token) %>
    <p>
        <label for="email">가입하신 이메일</label>
        <input name="email" type="text">
    </p>
    <button type="submit">확인</button>
</form>

app/views/user/login.html.erb
<h1>User#login</h1>
<p>Find me in app/views/user/login.html.erb</p>

app/views/user/login_form.html.erb
<h1>로그인</h1>
<form action="/user/login" method="post">
    <%= hidden_field_tag(request_forgery_protection_token.to_s, form_authenticity_token) %>
    <p>
        <label for="account">계정</label>
        <input name="account" type="text">
    </p>
    <p>
        <label for="password">비밀번호</label>
        <input name="password" type="password">
    </p>
    <button type="submit">로그인</button>
    <a href="/user/forgot_form">비밀번호 찾기</a>
</form>

app/views/user/logout.html.erb
<h1>User#logout</h1>
<p>Find me in app/views/user/logout.html.erb</p>

app/views/user/new.html.erb
<h1>회원가입</h1>
<form action="/user/create" method="post">
    <%= hidden_field_tag(request_forgery_protection_token.to_s, form_authenticity_token) %>
    <p>
        <label for="account">계정</label>
        <input type="text" name="account">
    </p>
    <p>
        <label for="email">이메일</label>
        <input type="text" name="email">
    </p>
    <p>
        <label for="password">비밀번호</label>
        <input type="password" name="password">
    </p>
    <p>
        <label for="name">사용자명</label>
        <input type="text" name="name">
    </p>
    <button type="submit">가입</button>
</form>